[theme]
primaryColor = "#FF9797"
backgroundColor = "#FFF4F4"
secondaryBackgroundColor = "#FFCECE"
textColor = "#2E2F37"

# This can be one of the following: (tipografías)
# - "sans-serif"
# - "serif"
# - "monospace"
font = "serif"
