# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11pzPgb-vhYvgUTLJKYkaq_GPhj3Rdz9f
"""

import streamlit as st
import pandas as pd

# Carga la base de datos
@st.cache_data
def load_data():
    return pd.read_excel('Base de datos (1).xlsx')
df = load_data()

emociones = ['alegre', 'triste', 'relajado', 'romantico', 'divertido', 'motivado', 'estresado', 'ansioso', 'molesto']
opciones_duracion = df['duracion'].dropna().unique()
opciones_idioma = ['español', 'inglés']

mejora_map = {
    'triste': 'motivado',
    'estresado': 'relajado',
    'ansioso': 'relajado',
    'molesto': 'relajado'
}

st.title('🎵 Recomendador de Canciones por Emoción')
st.write('Elige tus opciones y recibe una canción sugerida según cómo te sientes y tus preferencias.')

# Paso 1: Emoción
st.subheader('1. ¿Cómo te sientes hoy? (Emoción)')
emocion = st.selectbox('Selecciona una emoción:', emociones, key='emocion')

# Paso 2: Propósito si corresponde
proposito = None
if emocion in ['triste', 'estresado', 'ansioso', 'molesto']:
    st.subheader('2. ¿Qué buscas en la canción?')
    proposito = st.radio('',
        ['Que acompañe lo que siento', 'Que mejore mi estado de ánimo'], key='proposito')

# Paso 3: Duración
st.subheader('3. ¿Prefieres una canción corta o larga?')
duracion_elegida = st.radio('', opciones_duracion, key='duracion')

# Paso 4: Idioma
st.subheader('4. ¿En qué idioma prefieres la canción?')
idioma = st.radio('', opciones_idioma, key='idioma')

# Paso 5: Año
st.subheader('5. ¿De qué época prefieres la canción?')
epoca = st.radio('', ['hasta 2010', 'desde 2011'], key='epoca')

# Determinar emoción final para filtro
if proposito and proposito == 'Que mejore mi estado de ánimo':
    emocion_query = mejora_map.get(emocion, emocion)
else:
    emocion_query = emocion

# Realizar filtro al presionar el botón
if st.button('🎶 Recomiéndame una canción'):
    filtro = (
        (df['emocion'].str.lower() == emocion_query.lower()) &
        (df['duracion'].str.lower() == duracion_elegida.lower()) &
        (df['idioma'].str.lower() == idioma.lower()) &
        ((df['año_exacto'] <= 2010) if epoca == 'hasta 2010' else (df['año_exacto'] >= 2011))
    )
    resultado = df[filtro]
    if not resultado.empty:
        cancion = resultado.sample(1).iloc[0]
        st.success('¡Aquí tienes tu canción sugerida!')
        st.markdown(f"**{cancion['nombre_cancion']}** — {cancion['nombre_artista']}  ")
        st.markdown(f"Género: {cancion['genero']}")
        if pd.notnull(cancion['foto_artista']):
            st.image(cancion['foto_artista'], width=200)
        st.markdown(f"Red social: [{cancion['red_social']}]({cancion['link_red_social']})")
        st.markdown(f"\n**Letra:**\n{cancion['letra_cancion']}")
        st.markdown(f"\n**Información:** {cancion['info_cancion']}")
        st.markdown(f"\n[Spotify]({cancion['url_spotify']}) | [Video]({cancion['url_video']})")
    else:
        st.warning('No se encontraron canciones para tu selección.')