[theme]
primaryColor = "#69946F"
backgroundColor = "#AEC3B0"
secondaryBackgroundColor = "#EFF6E0"
textColor = "#2D2D2D"

# This can be one of the following: (tipografías)
# - "sans-serif"
# - "serif"
# - "monospace"
font = "monospace"
